service: api-pelicula
org: danielcaballeros

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::397279833444:role/LabRole
  environment:
    TABLE_NAME_PELICULA: ${sls:stage}-tp_pelicula
    LAMBDA_VALIDAR_TOKEN: api-usuarios-${sls:stage}-validar_token

functions:
  crearPelicula:
    handler: crearPelicula.handler
    events:
      - http:
          path: /pelicula
          method: post
          cors: true
          integration: lambda

  obtenerPeliculaById:
    handler: obtenerPeliculaById.handler
    events:
      - http:
          path: /pelicula/{uuid}  # Usamos solo uuid como variable en el path
          method: get
          cors: true
          integration: lambda

  obtenerPeliculas:
    handler: obtenerPeliculas.handler
    events:
      - http:
          path: /peliculas
          method: get
          cors: true
          integration: lambda

  modificarPelicula:
    handler: modificarPelicula.handler
    events:
      - http:
          path: /pelicula/{tenant_id}/{titulo}
          method: put
          cors: true
          integration: lambda

  eliminarPelicula:
    handler: eliminarPelicula.handler
    events:
      - http:
          path: /pelicula/{tenant_id}/{titulo}
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    PeliculasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PELICULA}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: genero
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        # Índice Secundario Local (LSI)
        LocalSecondaryIndexes:
          - IndexName: GeneroIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: genero
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
