service: api-pelicula
org: danielcaballeros

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::397279833444:role/LabRole
  environment:
    TABLE_NAME_PELICULA: ${self:provider.stage}-tp_pelicula

functions:
  crearPelicula:
    handler: crearPelicula.handler
    events:
      - http:
          path: /pelicula
          method: post
          cors: true

  obtenerPeliculaById:
    handler: obtenerPeliculaById.handler
    events:
      - http:
          path: /pelicula/{tenant_id}/{titulo}
          method: get
          cors: true

  obtenerPeliculas:
    handler: obtenerPeliculas.handler
    events:
      - http:
          path: /peliculas
          method: get
          cors: true

  modificarPelicula:
    handler: modificarPelicula.handler
    events:
      - http:
          path: /pelicula/{tenant_id}/{titulo}
          method: put
          cors: true

  eliminarPelicula:
    handler: eliminarPelicula.handler
    events:
      - http:
          path: /pelicula
          method: delete
          cors: true

resources:
  Resources:
    PeliculasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PELICULA}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: titulo
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: titulo
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
